// Copyright (C) Parity Technologies and the various Paseo contributors, see Contributions.md
// for a list of specific contributors.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `indiv_pallet_pgas`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-10-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `b3c9d4e631ff`, CPU: `QEMU Virtual CPU version 2.5+`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/asset-hub-paseo-runtime/asset_hub_paseo_runtime.wasm
// --pallet=indiv_pallet_pgas
// --genesis-builder=runtime
// --genesis-builder-preset=local_testnet
// --wasm-execution=compiled
// --heap-pages=4096
// --min-duration
// 1
// --quiet
// --steps=50
// --repeat=20
// --header=/_work/gh-runner-03/runtimes/runtimes/.bench-tools/.github/scripts/cmd/file_header.txt
// --output=/tmp/bench-2ddvse42

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `indiv_pallet_pgas`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> indiv_pallet_pgas::WeightInfo for WeightInfo<T> {
	/// Storage: `Pgas::ClaimedGasAliases` (r:1 w:1)
	/// Proof: `Pgas::ClaimedGasAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Revive::OriginalAccount` (r:1 w:1)
	/// Proof: `Revive::OriginalAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn claim_pgas() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3748`
		//  Estimated: `3675`
		// Minimum execution time: 45_505_000 picoseconds.
		Weight::from_parts(49_192_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Pgas::ClaimedGasAliases` (r:5 w:5)
	/// Proof: `Pgas::ClaimedGasAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Revive::OriginalAccount` (r:1 w:1)
	/// Proof: `Revive::OriginalAccount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn batch_claim_pgas() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3748`
		//  Estimated: `13625`
		// Minimum execution time: 105_518_000 picoseconds.
		Weight::from_parts(115_697_000, 0)
			.saturating_add(Weight::from_parts(0, 13625))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::NextAssetId` (r:1 w:0)
	/// Proof: `Assets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn create_pgas_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3675`
		// Minimum execution time: 10_991_000 picoseconds.
		Weight::from_parts(11_973_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn authorize_create_pgas_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3675`
		// Minimum execution time: 3_066_000 picoseconds.
		Weight::from_parts(3_447_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Pgas::ClaimedGasAliases` (r:21 w:20)
	/// Proof: `Pgas::ClaimedGasAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 20]`.
	fn clean_pgas_claim_records(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `175 + n * (53 ±0)`
		//  Estimated: `3517 + n * (2527 ±0)`
		// Minimum execution time: 12_443_000 picoseconds.
		Weight::from_parts(14_709_170, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			// Standard Error: 5_635
			.saturating_add(Weight::from_parts(739_978, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2527).saturating_mul(n.into()))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Pgas::ClaimedGasAliases` (r:1 w:0)
	/// Proof: `Pgas::ClaimedGasAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn authorize_clean_pgas_claim_records() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `300`
		//  Estimated: `3517`
		// Minimum execution time: 7_234_000 picoseconds.
		Weight::from_parts(7_654_000, 0)
			.saturating_add(Weight::from_parts(0, 3517))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionExponents` (r:1 w:0)
	/// Proof: `MembersSubscriber::RingCollectionExponents` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::CurrentGeneration` (r:1 w:0)
	/// Proof: `MembersSubscriber::CurrentGeneration` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingRoots` (r:1 w:0)
	/// Proof: `MembersSubscriber::RingRoots` (`max_values`: None, `max_size`: Some(1005), added: 3480, mode: `MaxEncodedLen`)
	/// Storage: `Pgas::ClaimedGasAliases` (r:1 w:0)
	/// Proof: `Pgas::ClaimedGasAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn as_pgas_claim_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `898`
		//  Estimated: `4470`
		// Minimum execution time: 19_821_447_000 picoseconds.
		Weight::from_parts(20_010_732_000, 0)
			.saturating_add(Weight::from_parts(0, 4470))
			.saturating_add(T::DbWeight::get().reads(7))
	}
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `NetworkSuffix::NetworkSuffix` (r:1 w:0)
	/// Proof: `NetworkSuffix::NetworkSuffix` (`max_values`: Some(1), `max_size`: Some(17), added: 512, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingCollectionExponents` (r:1 w:0)
	/// Proof: `MembersSubscriber::RingCollectionExponents` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::CurrentGeneration` (r:1 w:0)
	/// Proof: `MembersSubscriber::CurrentGeneration` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `MembersSubscriber::RingRoots` (r:1 w:0)
	/// Proof: `MembersSubscriber::RingRoots` (`max_values`: None, `max_size`: Some(1005), added: 3480, mode: `MaxEncodedLen`)
	/// Storage: `Pgas::ClaimedGasAliases` (r:5 w:0)
	/// Proof: `Pgas::ClaimedGasAliases` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn as_pgas_batch_claim_tx_ext() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `898`
		//  Estimated: `13625`
		// Minimum execution time: 23_718_025_000 picoseconds.
		Weight::from_parts(23_875_430_000, 0)
			.saturating_add(Weight::from_parts(0, 13625))
			.saturating_add(T::DbWeight::get().reads(11))
	}
}
