[package]
name = "indiv-support"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
ark-bls12-381-ext = { workspace = true }
ark-ec = { workspace = true }
ark-ed-on-bls12-381-bandersnatch-ext = { workspace = true }
ark-ff = { workspace = true }
ark-scale = { workspace = true, features = ["ec"] }
codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
frame-support = { workspace = true }
frame-system = { workspace = true }
getrandom = { workspace = true, optional = true }
sp-core = { workspace = true }
sp-crypto-ec-utils = { workspace = true, features = ["bls12-381", "ed-on-bls12-381-bandersnatch"] }
sp-crypto-hashing = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-statement-store = { workspace = true }
spin = { workspace = true }
verifiable = { workspace = true }
pallet-asset-tx-payment = { workspace = true }
pallet-asset-conversion-tx-payment = { workspace = true }
pallet-transaction-payment = { workspace = true }

[dev-dependencies]
pallet-balances = { workspace = true }
pallet-assets = { workspace = true }
pallet-asset-conversion = { workspace = true }

[features]
default = ["std"]
std = [
	"ark-bls12-381-ext/std",
	"ark-ec/std",
	"ark-ed-on-bls12-381-bandersnatch-ext/std",
	"ark-ff/std",
	"ark-scale/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"getrandom?/std",
	"pallet-asset-conversion-tx-payment/std",
	"pallet-asset-conversion/std",
	"pallet-asset-tx-payment/std",
	"pallet-assets/std",
	"pallet-balances/std",
	"pallet-transaction-payment/std",
	"prover",
	"scale-info/std",
	"sp-core/std",
	"sp-crypto-ec-utils/std",
	"sp-crypto-hashing/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-statement-store/std",
	"spin/std",
	"verifiable/std",
]
ec-crypto-hostcalls = []
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"getrandom/custom",
	"pallet-asset-conversion-tx-payment/runtime-benchmarks",
	"pallet-asset-conversion/runtime-benchmarks",
	"pallet-asset-tx-payment/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-transaction-payment/runtime-benchmarks",
	"prover",
	"sp-runtime/runtime-benchmarks",
	"verifiable/builder-params",
	"verifiable/no-std-prover",
]
genesis = ["verifiable/builder-params"]
prover = ["verifiable/prover"]
