[package]
name = "indiv-precompile-personhood"
description = "Pallet-revive precompile for proof of personhood status verification"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { workspace = true, features = ["derive"] }
frame-support = { workspace = true }
frame-system = { workspace = true }
indiv-support = { workspace = true }
log = { workspace = true }
pallet-revive = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
indiv-pallet-alias-accounts = { workspace = true }
indiv-pallet-members-subscriber = { workspace = true }
pallet-assets = { workspace = true }
pallet-balances = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
verifiable = { workspace = true, features = ["mock"] }
xcm = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"indiv-pallet-alias-accounts/std",
	"indiv-pallet-members-subscriber/std",
	"indiv-support/std",
	"log/std",
	"pallet-assets/std",
	"pallet-balances/std",
	"pallet-revive/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"verifiable/std",
	"xcm/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"indiv-pallet-alias-accounts/runtime-benchmarks",
	"indiv-pallet-members-subscriber/runtime-benchmarks",
	"indiv-support/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-revive/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"indiv-pallet-alias-accounts/try-runtime",
	"indiv-pallet-members-subscriber/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-revive/try-runtime",
	"sp-runtime/try-runtime",
]
