// Copyright (C) Parity Technologies and the various Paseo contributors, see Contributions.md
// for a list of specific contributors.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `indiv_pallet_members`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 58.0.0
//! DATE: 2026-09-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `5d075a2a3f2a`, CPU: `QEMU Virtual CPU version 2.5+`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --extrinsic=*
// --runtime=target/production/wbuild/people-paseo-runtime/people_paseo_runtime.wasm
// --pallet=indiv_pallet_members
// --genesis-builder=runtime
// --genesis-builder-preset=local_testnet
// --wasm-execution=compiled
// --heap-pages=4096
// --min-duration
// 1
// --quiet
// --steps=50
// --repeat=20
// --header=/_work/gh-runner-03/runtimes/runtimes/.bench-tools/.github/scripts/cmd/file_header.txt
// --output=/tmp/bench-2kut5nx_

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `indiv_pallet_members`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> indiv_pallet_members::WeightInfo for WeightInfo<T> {
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingSize` (r:0 w:1)
	/// Proof: `Members::OnboardingSize` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn set_onboarding_size() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `206`
		//  Estimated: `4111`
		// Minimum execution time: 9_959_000 picoseconds.
		Weight::from_parts(10_860_000, 0)
			.saturating_add(Weight::from_parts(0, 4111))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::CurrentRingIndex` (r:1 w:0)
	/// Proof: `Members::CurrentRingIndex` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeys` (r:2 w:2)
	/// Proof: `Members::RingKeys` (`max_values`: None, `max_size`: Some(8226), added: 10701, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:2)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::PendingSuspensions` (r:2 w:0)
	/// Proof: `Members::PendingSuspensions` (`max_values`: None, `max_size`: Some(1066), added: 3541, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:126 w:126)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:1)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribedCollections` (r:1 w:0)
	/// Proof: `MembersNotifier::SubscribedCollections` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageState` (r:1 w:1)
	/// Proof: `MembersNotifier::PageState` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PendingUpdates` (r:1 w:1)
	/// Proof: `MembersNotifier::PendingUpdates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageUpdatesCount` (r:2 w:1)
	/// Proof: `MembersNotifier::PageUpdatesCount` (`max_values`: None, `max_size`: Some(6), added: 2481, mode: `MaxEncodedLen`)
	/// Storage: `Members::StaleRings` (r:0 w:2)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Members::OldRoots` (r:0 w:1)
	/// Proof: `Members::OldRoots` (`max_values`: None, `max_size`: Some(336), added: 2811, mode: `MaxEncodedLen`)
	fn merge_rings() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `27595`
		//  Estimated: `324558`
		// Minimum execution time: 833_684_000 picoseconds.
		Weight::from_parts(860_183_000, 0)
			.saturating_add(Weight::from_parts(0, 324558))
			.saturating_add(T::DbWeight::get().reads(141))
			.saturating_add(T::DbWeight::get().writes(137))
	}
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::PendingSuspensions` (r:1 w:0)
	/// Proof: `Members::PendingSuspensions` (`max_values`: None, `max_size`: Some(1066), added: 3541, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:0)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn should_build_ring(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `4531`
		// Minimum execution time: 13_786_000 picoseconds.
		Weight::from_parts(14_431_742, 0)
			.saturating_add(Weight::from_parts(0, 4531))
			.saturating_add(T::DbWeight::get().reads(4))
	}
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:1)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:1)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeys` (r:1 w:0)
	/// Proof: `Members::RingKeys` (`max_values`: None, `max_size`: Some(8226), added: 10701, mode: `MaxEncodedLen`)
	/// Storage: `ChunksManager::Chunks` (r:1 w:0)
	/// Proof: `ChunksManager::Chunks` (`max_values`: None, `max_size`: Some(24503), added: 26978, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribedCollections` (r:1 w:0)
	/// Proof: `MembersNotifier::SubscribedCollections` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageState` (r:1 w:1)
	/// Proof: `MembersNotifier::PageState` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PendingUpdates` (r:1 w:1)
	/// Proof: `MembersNotifier::PendingUpdates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageUpdatesCount` (r:2 w:1)
	/// Proof: `MembersNotifier::PageUpdatesCount` (`max_values`: None, `max_size`: Some(6), added: 2481, mode: `MaxEncodedLen`)
	/// Storage: `Members::StaleRings` (r:0 w:1)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Members::OldRoots` (r:0 w:1)
	/// Proof: `Members::OldRoots` (`max_values`: None, `max_size`: Some(336), added: 2811, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn build_ring_r2e9(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `34836`
		//  Estimated: `27968`
		// Minimum execution time: 3_682_277_000 picoseconds.
		Weight::from_parts(6_716_235_863, 0)
			.saturating_add(Weight::from_parts(0, 27968))
			// Standard Error: 3_087_371
			.saturating_add(Weight::from_parts(798_854_353, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:1)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:1)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeys` (r:2 w:0)
	/// Proof: `Members::RingKeys` (`max_values`: None, `max_size`: Some(8226), added: 10701, mode: `MaxEncodedLen`)
	/// Storage: `ChunksManager::Chunks` (r:2 w:0)
	/// Proof: `ChunksManager::Chunks` (`max_values`: None, `max_size`: Some(24503), added: 26978, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribedCollections` (r:1 w:0)
	/// Proof: `MembersNotifier::SubscribedCollections` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageState` (r:1 w:1)
	/// Proof: `MembersNotifier::PageState` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PendingUpdates` (r:1 w:1)
	/// Proof: `MembersNotifier::PendingUpdates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageUpdatesCount` (r:2 w:1)
	/// Proof: `MembersNotifier::PageUpdatesCount` (`max_values`: None, `max_size`: Some(6), added: 2481, mode: `MaxEncodedLen`)
	/// Storage: `Members::OldRoots` (r:0 w:1)
	/// Proof: `Members::OldRoots` (`max_values`: None, `max_size`: Some(336), added: 2811, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn build_ring_r2e10(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `59364 + n * (32 ±0)`
		//  Estimated: `52822 + n * (32 ±18)`
		// Minimum execution time: 3_681_635_000 picoseconds.
		Weight::from_parts(6_899_567_296, 0)
			.saturating_add(Weight::from_parts(0, 52822))
			// Standard Error: 3_041_293
			.saturating_add(Weight::from_parts(800_317_128, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(n.into()))
	}
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:1)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:1)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeys` (r:2 w:0)
	/// Proof: `Members::RingKeys` (`max_values`: None, `max_size`: Some(8226), added: 10701, mode: `MaxEncodedLen`)
	/// Storage: `ChunksManager::Chunks` (r:2 w:0)
	/// Proof: `ChunksManager::Chunks` (`max_values`: None, `max_size`: Some(24503), added: 26978, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribedCollections` (r:1 w:0)
	/// Proof: `MembersNotifier::SubscribedCollections` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageState` (r:1 w:1)
	/// Proof: `MembersNotifier::PageState` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PendingUpdates` (r:1 w:1)
	/// Proof: `MembersNotifier::PendingUpdates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageUpdatesCount` (r:2 w:1)
	/// Proof: `MembersNotifier::PageUpdatesCount` (`max_values`: None, `max_size`: Some(6), added: 2481, mode: `MaxEncodedLen`)
	/// Storage: `Members::OldRoots` (r:0 w:1)
	/// Proof: `Members::OldRoots` (`max_values`: None, `max_size`: Some(336), added: 2811, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn build_ring_r2e14(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60030 + n * (32 ±0)`
		//  Estimated: `52822 + n * (32 ±7)`
		// Minimum execution time: 3_687_627_000 picoseconds.
		Weight::from_parts(6_880_987_323, 0)
			.saturating_add(Weight::from_parts(0, 52822))
			// Standard Error: 3_019_535
			.saturating_add(Weight::from_parts(800_400_690, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(n.into()))
	}
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::PendingSuspensions` (r:1 w:0)
	/// Proof: `Members::PendingSuspensions` (`max_values`: None, `max_size`: Some(1066), added: 3541, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:0)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn ensure_can_build_ring() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1736`
		//  Estimated: `4657`
		// Minimum execution time: 31_489_000 picoseconds.
		Weight::from_parts(32_261_000, 0)
			.saturating_add(Weight::from_parts(0, 4657))
			.saturating_add(T::DbWeight::get().reads(6))
	}
	/// Storage: `Members::RingDeletionQueue` (r:1 w:0)
	/// Proof: `Members::RingDeletionQueue` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	fn ensure_can_delete_ring_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158`
		//  Estimated: `3521`
		// Minimum execution time: 6_473_000 picoseconds.
		Weight::from_parts(6_813_000, 0)
			.saturating_add(Weight::from_parts(0, 3521))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::PendingSuspensions` (r:1 w:0)
	/// Proof: `Members::PendingSuspensions` (`max_values`: None, `max_size`: Some(1066), added: 3541, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:0)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	fn ensure_can_remove_suspended_keys() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2755`
		//  Estimated: `4657`
		// Minimum execution time: 28_844_000 picoseconds.
		Weight::from_parts(29_786_000, 0)
			.saturating_add(Weight::from_parts(0, 4657))
			.saturating_add(T::DbWeight::get().reads(4))
	}
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:1 w:0)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:2 w:0)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	fn ensure_can_merge_queue_pages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `8531`
		//  Estimated: `22352`
		// Minimum execution time: 20_718_000 picoseconds.
		Weight::from_parts(21_230_000, 0)
			.saturating_add(Weight::from_parts(0, 22352))
			.saturating_add(T::DbWeight::get().reads(4))
	}
	/// Storage: `Members::CurrentRingIndex` (r:1 w:0)
	/// Proof: `Members::CurrentRingIndex` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:1 w:0)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:0)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingSize` (r:1 w:0)
	/// Proof: `Members::OnboardingSize` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:2 w:0)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::PendingSuspensions` (r:1 w:0)
	/// Proof: `Members::PendingSuspensions` (`max_values`: None, `max_size`: Some(1066), added: 3541, mode: `MaxEncodedLen`)
	fn ensure_can_onboard_members() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `12947`
		//  Estimated: `22352`
		// Minimum execution time: 43_001_000 picoseconds.
		Weight::from_parts(44_133_000, 0)
			.saturating_add(Weight::from_parts(0, 22352))
			.saturating_add(T::DbWeight::get().reads(10))
	}
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::CurrentRingIndex` (r:1 w:1)
	/// Proof: `Members::CurrentRingIndex` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:1)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeys` (r:2 w:1)
	/// Proof: `Members::RingKeys` (`max_values`: None, `max_size`: Some(8226), added: 10701, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:1 w:1)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:2 w:2)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingSize` (r:1 w:0)
	/// Proof: `Members::OnboardingSize` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::PendingSuspensions` (r:1 w:0)
	/// Proof: `Members::PendingSuspensions` (`max_values`: None, `max_size`: Some(1066), added: 3541, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:255 w:255)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::ActiveMembers` (r:1 w:1)
	/// Proof: `Members::ActiveMembers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::StaleRings` (r:0 w:1)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn onboard_members() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40346`
		//  Estimated: `655830`
		// Minimum execution time: 1_540_940_000 picoseconds.
		Weight::from_parts(1_565_176_000, 0)
			.saturating_add(Weight::from_parts(0, 655830))
			.saturating_add(T::DbWeight::get().reads(268))
			.saturating_add(T::DbWeight::get().writes(263))
	}
	/// Storage: `Members::PendingSuspensions` (r:2 w:0)
	/// Proof: `Members::PendingSuspensions` (`max_values`: None, `max_size`: Some(1066), added: 3541, mode: `MaxEncodedLen`)
	fn pending_suspensions_iteration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1485`
		//  Estimated: `8072`
		// Minimum execution time: 10_890_000 picoseconds.
		Weight::from_parts(11_231_000, 0)
			.saturating_add(Weight::from_parts(0, 8072))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeys` (r:1 w:1)
	/// Proof: `Members::RingKeys` (`max_values`: None, `max_size`: Some(8226), added: 10701, mode: `MaxEncodedLen`)
	/// Storage: `Members::PendingSuspensions` (r:1 w:1)
	/// Proof: `Members::PendingSuspensions` (`max_values`: None, `max_size`: Some(1066), added: 3541, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:255 w:255)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:1)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::ActiveMembers` (r:1 w:1)
	/// Proof: `Members::ActiveMembers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::Root` (r:1 w:1)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Members::StaleRings` (r:0 w:1)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Members::OldRoots` (r:0 w:1)
	/// Proof: `Members::OldRoots` (`max_values`: None, `max_size`: Some(336), added: 2811, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 255]`.
	fn remove_suspended_keys(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `17097 + n * (42 ±0)`
		//  Estimated: `11691 + n * (2568 ±0)`
		// Minimum execution time: 437_641_000 picoseconds.
		Weight::from_parts(466_569_311, 0)
			.saturating_add(Weight::from_parts(0, 11691))
			// Standard Error: 9_070
			.saturating_add(Weight::from_parts(3_870_105, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(7))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2568).saturating_mul(n.into()))
	}
	/// Storage: `Members::Members` (r:254 w:254)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:1 w:1)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:0 w:2)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	fn merge_queue_pages() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `17327`
		//  Estimated: `653262`
		// Minimum execution time: 1_392_592_000 picoseconds.
		Weight::from_parts(1_424_412_000, 0)
			.saturating_add(Weight::from_parts(0, 653262))
			.saturating_add(T::DbWeight::get().reads(255))
			.saturating_add(T::DbWeight::get().writes(257))
	}
	/// Storage: `Members::StaleRings` (r:10 w:0)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	fn build_rings_base(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `101 + n * (48 ±0)`
		//  Estimated: `3672 + n * (2474 ±11)`
		// Minimum execution time: 4_128_000 picoseconds.
		Weight::from_parts(3_964_009, 0)
			.saturating_add(Weight::from_parts(0, 3672))
			// Standard Error: 2_646
			.saturating_add(Weight::from_parts(938_218, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2474).saturating_mul(n.into()))
	}
	/// Storage: `Members::Root` (r:1 w:1)
	/// Proof: `Members::Root` (`max_values`: None, `max_size`: Some(1192), added: 3667, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::SubscribedCollections` (r:1 w:0)
	/// Proof: `MembersNotifier::SubscribedCollections` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageState` (r:1 w:1)
	/// Proof: `MembersNotifier::PageState` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PendingUpdates` (r:1 w:1)
	/// Proof: `MembersNotifier::PendingUpdates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `MembersNotifier::PageUpdatesCount` (r:2 w:1)
	/// Proof: `MembersNotifier::PageUpdatesCount` (`max_values`: None, `max_size`: Some(6), added: 2481, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:1)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::ActiveMembers` (r:1 w:1)
	/// Proof: `Members::ActiveMembers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::StaleRings` (r:0 w:1)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingDeletionQueue` (r:0 w:64)
	/// Proof: `Members::RingDeletionQueue` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Members::OldRoots` (r:0 w:1)
	/// Proof: `Members::OldRoots` (`max_values`: None, `max_size`: Some(336), added: 2811, mode: `MaxEncodedLen`)
	/// Storage: `Members::PendingSuspensions` (r:0 w:1)
	/// Proof: `Members::PendingSuspensions` (`max_values`: None, `max_size`: Some(1066), added: 3541, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 64]`.
	fn enqueue_ring_deletion_authorized(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1779`
		//  Estimated: `5952`
		// Minimum execution time: 61_926_000 picoseconds.
		Weight::from_parts(61_517_721, 0)
			.saturating_add(Weight::from_parts(0, 5952))
			// Standard Error: 6_010
			.saturating_add(Weight::from_parts(2_871_532, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(9))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
	}
	/// Storage: `Members::OnboardingQueue` (r:1 w:1)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:0 w:255)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 255]`.
	fn delete_onboarding_queue_page_authorized(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `286 + n * (32 ±0)`
		//  Estimated: `11671`
		// Minimum execution time: 6_322_000 picoseconds.
		Weight::from_parts(7_552_654, 0)
			.saturating_add(Weight::from_parts(0, 11671))
			// Standard Error: 1_744
			.saturating_add(Weight::from_parts(1_599_157, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
	}
	/// Storage: `Members::SuspendedCollections` (r:1 w:1)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::IdentifiersOf` (r:1 w:1)
	/// Proof: `Members::IdentifiersOf` (`max_values`: None, `max_size`: Some(3821), added: 6296, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:0 w:1)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::ActiveMembers` (r:0 w:1)
	/// Proof: `Members::ActiveMembers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::CurrentRingIndex` (r:0 w:1)
	/// Proof: `Members::CurrentRingIndex` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:0 w:1)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingSize` (r:0 w:1)
	/// Proof: `Members::OnboardingSize` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn finalize_collection_deletion_authorized() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3455`
		//  Estimated: `7286`
		// Minimum execution time: 20_759_000 picoseconds.
		Weight::from_parts(21_791_000, 0)
			.saturating_add(Weight::from_parts(0, 7286))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Members::Members` (r:501 w:500)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 500]`.
	fn remove_orphaned_members_authorized(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `250 + n * (54 ±0)`
		//  Estimated: `3558 + n * (2568 ±0)`
		// Minimum execution time: 11_562_000 picoseconds.
		Weight::from_parts(12_023_000, 0)
			.saturating_add(Weight::from_parts(0, 3558))
			// Standard Error: 3_532
			.saturating_add(Weight::from_parts(4_045_141, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2568).saturating_mul(n.into()))
	}
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:0)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingDeletionQueue` (r:1 w:0)
	/// Proof: `Members::RingDeletionQueue` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:0)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:2 w:0)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	fn ensure_can_remove_orphaned_members() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `309`
		//  Estimated: `11671`
		// Minimum execution time: 18_915_000 picoseconds.
		Weight::from_parts(19_897_000, 0)
			.saturating_add(Weight::from_parts(0, 11671))
			.saturating_add(T::DbWeight::get().reads(6))
	}
	/// Storage: `Members::RingKeys` (r:1 w:1)
	/// Proof: `Members::RingKeys` (`max_values`: None, `max_size`: Some(8226), added: 10701, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:255 w:255)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingDeletionQueue` (r:0 w:1)
	/// Proof: `Members::RingDeletionQueue` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 255]`.
	fn delete_ring_page_authorized(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `361 + n * (98 ±0)`
		//  Estimated: `11691 + n * (2568 ±0)`
		// Minimum execution time: 20_429_000 picoseconds.
		Weight::from_parts(5_025_577, 0)
			.saturating_add(Weight::from_parts(0, 11691))
			// Standard Error: 4_732
			.saturating_add(Weight::from_parts(4_281_726, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2568).saturating_mul(n.into()))
	}
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:0)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn ensure_can_enqueue_ring_deletion() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `474`
		//  Estimated: `4111`
		// Minimum execution time: 10_340_000 picoseconds.
		Weight::from_parts(10_840_000, 0)
			.saturating_add(Weight::from_parts(0, 4111))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:0)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingDeletionQueue` (r:1 w:0)
	/// Proof: `Members::RingDeletionQueue` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:0)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	fn ensure_can_delete_onboarding_queue_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `458`
		//  Estimated: `11671`
		// Minimum execution time: 15_970_000 picoseconds.
		Weight::from_parts(16_751_000, 0)
			.saturating_add(Weight::from_parts(0, 11671))
			.saturating_add(T::DbWeight::get().reads(4))
	}
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:0)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingDeletionQueue` (r:1 w:0)
	/// Proof: `Members::RingDeletionQueue` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:0)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:0)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	fn ensure_can_finalize_collection_deletion() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `206`
		//  Estimated: `11671`
		// Minimum execution time: 16_121_000 picoseconds.
		Weight::from_parts(16_972_000, 0)
			.saturating_add(Weight::from_parts(0, 11671))
			.saturating_add(T::DbWeight::get().reads(5))
	}
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:1)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:1)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Members::QueuePageIndices` (r:1 w:1)
	/// Proof: `Members::QueuePageIndices` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `Members::CurrentRingIndex` (r:1 w:0)
	/// Proof: `Members::CurrentRingIndex` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:1)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeys` (r:1 w:1)
	/// Proof: `Members::RingKeys` (`max_values`: None, `max_size`: Some(8226), added: 10701, mode: `MaxEncodedLen`)
	/// Storage: `Members::ActiveMembers` (r:1 w:1)
	/// Proof: `Members::ActiveMembers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::StaleRings` (r:0 w:1)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn self_include_remove_page() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `551`
		//  Estimated: `11691`
		// Minimum execution time: 44_413_000 picoseconds.
		Weight::from_parts(45_906_000, 0)
			.saturating_add(Weight::from_parts(0, 11691))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:1)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `Members::OnboardingQueue` (r:1 w:1)
	/// Proof: `Members::OnboardingQueue` (`max_values`: None, `max_size`: Some(8206), added: 10681, mode: `MaxEncodedLen`)
	/// Storage: `Members::CurrentRingIndex` (r:1 w:0)
	/// Proof: `Members::CurrentRingIndex` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:1)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeys` (r:1 w:1)
	/// Proof: `Members::RingKeys` (`max_values`: None, `max_size`: Some(8226), added: 10701, mode: `MaxEncodedLen`)
	/// Storage: `Members::ActiveMembers` (r:1 w:1)
	/// Proof: `Members::ActiveMembers` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Members::StaleRings` (r:0 w:1)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[2, 255]`.
	fn self_include_keep_page(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1052 + n * (33 ±0)`
		//  Estimated: `11691`
		// Minimum execution time: 44_263_000 picoseconds.
		Weight::from_parts(48_986_797, 0)
			.saturating_add(Weight::from_parts(0, 11691))
			// Standard Error: 703
			.saturating_add(Weight::from_parts(40_810, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Members::Collections` (r:1 w:0)
	/// Proof: `Members::Collections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingsState` (r:1 w:0)
	/// Proof: `Members::RingsState` (`max_values`: None, `max_size`: Some(34), added: 2509, mode: `MaxEncodedLen`)
	/// Storage: `Members::Members` (r:1 w:0)
	/// Proof: `Members::Members` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	fn validate_self_include() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `4111`
		// Minimum execution time: 1_325_946_000 picoseconds.
		Weight::from_parts(1_351_836_000, 0)
			.saturating_add(Weight::from_parts(0, 4111))
			.saturating_add(T::DbWeight::get().reads(4))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Members::OldRoots` (r:2 w:0)
	/// Proof: `Members::OldRoots` (`max_values`: None, `max_size`: Some(336), added: 2811, mode: `MaxEncodedLen`)
	fn ensure_can_clean_up_old_roots() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `796`
		//  Estimated: `6612`
		// Minimum execution time: 18_174_000 picoseconds.
		Weight::from_parts(18_705_000, 0)
			.saturating_add(Weight::from_parts(0, 6612))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Members::OldRoots` (r:101 w:100)
	/// Proof: `Members::OldRoots` (`max_values`: None, `max_size`: Some(336), added: 2811, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 100]`.
	fn clean_up_old_roots_authorized(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `496 + n * (303 ±0)`
		//  Estimated: `3801 + n * (2811 ±0)`
		// Minimum execution time: 26_129_000 picoseconds.
		Weight::from_parts(26_630_000, 0)
			.saturating_add(Weight::from_parts(0, 3801))
			// Standard Error: 170_179
			.saturating_add(Weight::from_parts(27_617_745, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2811).saturating_mul(n.into()))
	}
	/// Storage: `Members::SuspendedCollections` (r:1 w:0)
	/// Proof: `Members::SuspendedCollections` (`max_values`: None, `max_size`: Some(646), added: 3121, mode: `MaxEncodedLen`)
	/// Storage: `Members::StaleRings` (r:1 w:0)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Members::RingKeysStatus` (r:1 w:0)
	/// Proof: `Members::RingKeysStatus` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn ensure_can_mark_ring_stale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `439`
		//  Estimated: `4111`
		// Minimum execution time: 11_602_000 picoseconds.
		Weight::from_parts(12_002_000, 0)
			.saturating_add(Weight::from_parts(0, 4111))
			.saturating_add(T::DbWeight::get().reads(3))
	}
	/// Storage: `Members::StaleRings` (r:0 w:1)
	/// Proof: `Members::StaleRings` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn mark_ring_stale_authorized() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_039_000 picoseconds.
		Weight::from_parts(5_240_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
