name: "Rustfmt (check)"

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rustfmt:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set rust version via common env file
        run: cat .github/env >> $GITHUB_ENV

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          targets: "wasm32-unknown-unknown"
          components: "rustfmt"
          toolchain: "nightly-${{env.RUST_NIGHTLY_VERSION}}"

      - name: Rustfmt (check)
        run: cargo +nightly-$RUST_NIGHTLY_VERSION fmt --all -- --check
